{% set name = "itsxrust" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ayobi/ITSxRust/archive/refs/tags/v{{ version }}.tar.gz
  sha256: cd12fb2aad674bff6db5d12a88b6a992c7c0c04e083a133a91143943d11a72ec

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host: []
  run:
    - hmmer

test:
  commands:
    - itsxrust --help
    - itsxrust extract --help

about:
  summary: "ITSxRust is a tool for extracting ITS regions from DNA sequences."
  home: https://github.com/ayobi/ITSxRust
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - ayobi

