{% set name = "itsxrust" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ayobi/ITSxRust/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e453e9429df25d104ae3c57bbc3db20847a9a38aa22d4658c0941208bdb243f5

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host: []
  run:
    - hmmer

test:
  commands:
    - itsxrust --help
    - itsxrust extract --help

about:
  summary: "ITSxRust is a tool for extracting ITS regions from DNA sequences."
  home: https://github.com/ayobi/ITSxRust
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - ayobi

