{% set name = "fastqpacker" %}
{% set version = "0.8.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/vertti/fastqpacker/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6b117530b68246b74e7426d2273418328a7d432d328bd2888d7907d1c1333ff2

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('fastqpacker', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses

test:
  commands:
    - fqpack --version

about:
  home: "https://github.com/vertti/fastqpacker"
  summary: "Speed-first FASTQ compressor with block-based parallel compression"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: "https://github.com/vertti/fastqpacker"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - vertti
