{% set name = "pybigtools" %}
{% set version = "0.2.5" %}
{% set sha256 = "84c285000733d5073f9ac005f43384d9a64d5774dd1cb16d409c9bd3c05efc99" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('pybigtools', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - clangdev  # [osx]
  host:
    - pip
    - python
    - maturin
  run:
    - python
    - numpy

test:
  imports:
    - pybigtools

about:
  home: "https://github.com/jackh726/bigtools"
  license: MIT
  summary: 'pybigtools: Python bindings to the Bigtools Rust library for high-performance BigWig and BigBed I/O'
  license_family: MIT
  license_file: LICENSE
  doc_url: "https://bigtools.readthedocs.io"
  dev_url: "https://github.com/jackh726/bigtools"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - doi:10.5281/zenodo.10606493
