{% set name = "mtsv-tools" %}
{% set version = "2.1.0" %}
{% set sha256 = "bf2aced57d10321b5806f76ed10511f1f24bb8071317f364d8aea5fa4e2f7276" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/FofanovLab/mtsv_tools/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True # [osx]
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}
  script:
    - export C_INCLUDE_PATH="$PREFIX/include"
    - export LIBRARY_PATH="$PREFIX/lib"
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - cargo install -v --locked --no-track --root $PREFIX --path .

requirements:
  build:
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - {{ compiler('c') }}

test:
  commands:
    - mtsv-build --version


about:
  home: https://github.com/FofanovLab/mtsv_tools
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  license_family: MIT
  summary: |
    mtsv_tools contains core tools for alignment-based metagenomic/metatranscriptomic assignment

extra:
  recipe_maintainers: tfursten
    
