{% set name = 'r-bcalm' %}
{% set version = '0.99.0' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kircherlab/BCalm/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4eddd00013747719571162be907b416a8dc0963c0622932414f90cd49cb46be0

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  run_exports:
    - {{ pin_subpackage('r-bcalm', max_pin="x.x") }}

requirements:
  host:
    - r-base >=3.5
    - r-curl
    - bioconductor-biocgenerics
    - bioconductor-biobase
    - bioconductor-delayedarray
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-mpra
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-scales
    - r-statmod
    - r-tidyr
  run:
    - r-base >=3.5
    - r-curl
    - bioconductor-biocgenerics
    - bioconductor-biobase
    - bioconductor-delayedarray
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-mpra
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-scales
    - r-statmod
    - r-tidyr

test:
  commands:
    - $R -e "library('BCalm')"

about:
  home: https://github.com/kircherlab/BCalm
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Barcode Analysis using linear models for MPRA data'
  description: |
    BCalm is a package that provides a modification from the mpralm package, 
    an R package that provides tools for differential analysis in MPRA studies.
    BCalm allows users to use individual barcodes as model input. It provides 
    tools for data management, count preprocessing, and differential analysis 
    in massively parallel reporter assays (MPRA).
  dev_url: https://github.com/kircherlab/BCalm

extra:
  recipe-maintainers:
    - visze
