{% set name = "ebolaseq" %}
{% set version = "0.1.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/DaanJansen94/ebolaseq/archive/v{{ version }}.tar.gz
  sha256: db24c437f6df6c1fc6e1229d60e4a5b4d84eec611dc8f7343f3639a1fca5db34

build:
  number: 1
  noarch: python
  entry_points:
    - ebolaseq = ebolaseq.ebolaseq:cli_main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - biopython >=1.81
    - numpy >=1.20.0
    - mafft
    - trimal
    - iqtree =2.4.0 #iqtree=2.4.0: more reliable with ebolaseq than v3.0.1
    - minimap2
    - pal2nal

test:
  imports:
    - ebolaseq
  commands:
    - ebolaseq --help

about:
  home: "https://github.com/DaanJansen94/ebolaseq"
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: LICENSE
  summary: "Tool for downloading and analyzing Ebola virus sequences."
  description: |
    Ebolaseq is a command-line tool that simplifies the process of analyzing Ebola virus sequences. 
    It automates the complete workflow from downloading sequences to creating phylogenetic trees.
  doc_url: "https://github.com/DaanJansen94/ebolaseq/blob/v{{ version }}/README.md"
  dev_url: "https://github.com/DaanJansen94/ebolaseq"

extra:
  recipe-maintainers:
    - DaanJansen94
