{% set name = "pmultiqc" %}
{% set version = "0.0.41" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 68f1c2e035d90d2b965859ba8f31796891b3037bafba00211bf38087586a5f4a

build:
  number: 0
  noarch: python
  run_exports:
    - {{ pin_subpackage('pmultiqc', max_pin="x.x") }}
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.10,<3.13
    - pip
    - poetry-core
    - setuptools <78
  run:
    - python >=3.10,<3.13
    - pytest
    - lxml
    - multiqc >=1.29,<=1.32
    - pandas >=1.5
    - sdrf-pipelines >=0.0.33,<0.1.0
    - pyteomics
    - pyopenms <=3.4.0
    - numpy >=1.23
    - pyarrow
    - scikit-learn >=1.2
    - statsmodels
    - urllib3 >=2.6.1
    
test:
  requires:
    - setuptools <78
  imports:
    - pmultiqc
    - pmultiqc.modules
    - pmultiqc.modules.quantms

about:
  home: "https://github.com/bigbio/pmultiqc/"
  license: MIT
  license_family: MIT
  summary: "Python package for quality control of proteomics datasets, based on multiqc package"
  doc_url: https://github.com/bigbio/pmultiqc/
  dev_url: https://github.com/bigbio/pmultiqc/

extra:
  recipe-maintainers:
    - ypriverol
