{% set name = "pharmcat3" %}
{% set version = "3.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/PharmGKB/PharmCAT/releases/download/v{{ version }}/pharmcat-pipeline-{{ version }}.tar.gz
  sha256: 2902433d7fcbcb99df576edb4b14700b96aaf6752d9a586204892f772f969555

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}
  # script: bash build.sh

requirements:
  host:
    - python
  run:
    - openjdk >=17
    - python >=3.10
    - pandas
    - colorama
    - packaging
    - bcftools >=1.18
    - htslib >=1.18

test:
  commands:
    - pharmcat -version
    - pharmcat_pipeline -V
    - pharmcat_vcf_preprocessor -V

about:
  home: https://github.com/PharmGKB/PharmCAT
  summary: Pharmacogenomics Clinical Annotation Tool (PharmCAT) CLI, pipeline, and preprocessor.
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  doc_url: https://pharmcat.clinpgx.org/
  dev_url: https://github.com/PharmGKB/PharmCAT

extra:
  recipe-maintainers:
    - rkmishra3893
