{% set user = "USDA-VS" %}
{% set name = "vsnp3" %}
{% set version = "3.34" %}
{% set sha256 = "b62341a2254f86b4aefb39aa9da68dda2e85831e86e087c04cea6eb7599811b1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage('vsnp3', max_pin="x") }}

source:
  url: https://github.com/{{ user }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  run:
    - python >=3.8,<=3.12
    - bcftools
    - biopython >=1.79
    - bwa
    - minimap2 >=2.24
    - cairosvg >=2.5.2
    - dask >=2022.01.1
    - freebayes >=1.3.5
    - vcflib =1.0.12
    - humanize >=3.14.0
    - numpy >=1.16,<=1.26
    - pandas >=1.3,<=2.2
    - openpyxl >=3.0.9
    - xlsxwriter >=3.0.2
    - parallel
    - pigz
    - regex >=2.5.110
    - samtools >=1.14
    - seqkit >=2.1.0
    - sourmash >=4.2.4
    - spades >=3.15.2
    - svgwrite >=1.4.1
    - py-cpuinfo
    - raxml >=8.2.12
    - plotly
    
test:
  commands:
    - vsnp3_step1.py -h

about:
  home: https://github.com/{{ user }}/{{ name }}
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Rapidly call, validate, and compare SNPs from FASTQ files in a timely manner utilizing large data sets.
  dev_url: https://github.com/USDA-VS/vsnp3
