{% set name = "civicpy" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4dd1a4e064c7fe1cf097409707bdc5e3df38d137f199204de8d8a859c6b4fefc

build:
  number: 0
  noarch: python
  entry_points:
    - civicpy = civicpy.cli:cli
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir --use-pep517 -vvv
  run_exports:
    - {{ pin_subpackage('civicpy', max_pin="x") }}

requirements:
  host: 
    - pip
    - python >=3.10
    - setuptools
  run:
    - python >=3.10
    - backports
    - backports-datetime-fromisoformat
    - click
    - deprecation
    - networkx
    - obonet
    - pandas
    - pysam
    - requests
    - vcfpy

test:
  imports:
    - civicpy
  #commands:
    #- civicpy --help

about:
  home: "https://civicpy.org"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "CIViC variant knowledgebase analysis toolkit."
  doc_url: "https://docs.civicpy.org/en/latest"
  dev_url: "https://github.com/griffithlab/civicpy"
