{% set name = "ntsynt-viz" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bcgsc/ntSynt-viz/releases/download/v{{ version }}/ntSynt-viz-{{ version }}.tar.gz
  sha256: 411dfb12743ad950d8b8ad42dada000ae554670f521fdaeee1480813b452e953

build:
  number: 0
  noarch: generic
  run_exports: 
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  run:
    - python >=3.8
    - snakemake
    - quicktree
    - intervaltree
    - r-base
    - bioconductor-treeio
    - r-ggpubr 
    - bioconductor-ggtree 
    - r-phytools 
    - r-dplyr 
    - r-argparse 
    - r-scales 
    - r-stringr 
    - r-gggenomes
    - r-tidyr

test:
  commands:
    - ntsynt_viz.py --help

about:
  home: https://github.com/bcgsc/ntSynt-viz
  license: GPL-3.0
  license_file: LICENSE
  summary: 'Visualizing multi-genome synteny patterns'
  dev_url: https://github.com/bcgsc/ntSynt-viz
