{% set version = "1.5.6" %}
{% set name = "abPOA" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/yangao07/{{ name }}/releases/download/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: 60ef1cb65f8bf914949392e7bb755a92113f6724e9044db2431c64c1287e1c14

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name | lower, max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - zlib

test:
  commands:
    - {{ name | lower }} --version | grep {{ version }}

about:
  home: "https://github.com/yangao07/{{ name }}"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'abPOA: fast SIMD-based partial order alignment using adaptive band.'
  dev_url: "https://github.com/yangao07/{{ name }}"
  doc_url: "https://github.com/yangao07/abPOA/blob/v{{ version }}/README.md"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - doi:10.1093/bioinformatics/btaa963
    - biotools:abpoa
