pull_request_rules:
  - name: Approve and merge autobump PRs if tests are successful
    conditions:
      # Only commits by BiocondaBot, to ensure that the PR is not hijacked by others to introduce additional changes
      # PR may have multiple commits if there are other autobumps before first is merged
      - "commits[*].author=BiocondaBot"
      - "label=autobump"
      - created-at<3 days ago # note the operator direction: 3 days ago yield a timestamp pointing to 3 days ago, and we want to be smaller
      - "check-success=Linux Tests"
      - "check-success=OSX-64 Tests"
      - "check-success=build and test (ARM)"
      #- "check-success=bioconda.bioconda-recipes"
      - -closed
    actions:
      review:
        type: APPROVE
        message: Automatically approving successfull autobump
      merge:
        method: squash
