{% set name = "knock-knock" %}
{% set version = "0.8.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/knock_knock-{{ version }}.tar.gz"
  sha256: "3b58df139ac86e0c224e1cece7a96d799e41b71468d5374a8b1e3dd6bc92f55c"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv"
  run_exports:
    - {{ pin_subpackage('knock-knock', max_pin="x") }}

requirements:
  host:
    - pip
    - python >=3.12
    - setuptools
  run:
    - python >=3.12
    - bokeh >=2.4.2
    - anndata
    - biopython >=1.86
    - h5py >=3.1.0
    - ipywidgets >=7.1.2
    - matplotlib-base >=2.1.2
    - nbconvert >=6.0.7
    - nbformat >=4.4.0
    - numpy >=1.14.2
    - pandas >=0.22.0
    - pillow >=5.0.0
    - pysam >=0.14
    - pyyaml >=3.12
    - scipy >=1.16.2
    - pytables
    - hits >=0.4.3
    - tqdm >=4.31.1
    - viennarna >=2.6.4
    - blast >=2.7.1
    - minimap2 ==2.16
    - samtools >=1.9
    - star >=2.7.1
    - parallel >=20190522

test:
  imports:
    - knock_knock
  commands:
    - knock-knock -h
    - blastn -version
    - minimap2 --version
    - samtools --version
    - STAR --version

about:
  home: "https://github.com/jeffhussmann/knock-knock"
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: LICENSE
  summary: "toolkit for analyzing CRISPR knock-in experiments"

extra:
  recipe-maintainers:
    - jeffhussmann
