{% set name = "IsoQuant" %}
{% set version = "3.11.1" %}
{% set sha256 = "5a60639cc7f841d0203f7cf72144d26119a3db319a991a80700b6b5299212098" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ablab/IsoQuant/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x") }}

requirements:
  run:
    - python >=3.8,<3.14
    - argcomplete >=1.11.1
    - argh >=0.26.2
    - coverage >=7.6
    - editdistance >=0.6.2
    - gffutils >=0.10.1
    - minimap2 >=2.18
    - numba >=0.58
    - numpy >=1.24
    - packaging
    - pandas >=1.0.1
    - pyfaidx >=0.7
    - pysam >=0.15
    - pyyaml >=5.4
    - samtools >=1.14
    - scipy >=1.10
    - seaborn-base >=0.10.0
    - simplejson >=3.17.0
    - six >=1.14.0
    - star
    - ssw-py >=1.0

test:
  source_files:
    - tests
  commands:
    - isoquant.py --test
    - rm -rf isoquant_test

about:
  summary: "IsoQuant is a tool for reference-based analysis of long RNA reads, such as gene/transcript quantification and discovery."
  home: "https://github.com/ablab/IsoQuant"
  license: "GPL-2.0-or-later"
  license_family: GPL2
  license_file: LICENSE
  dev_url: "https://github.com/ablab/IsoQuant"
  doc_url: "https://ablab.github.io/IsoQuant"

extra:
  identifiers:
    - doi:10.1038/s41587-022-01565-y
