{% set name = "sassy" %}
{% set version = "0.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/ragnargrootkoerkamp/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 4082c3580259877c2aa633943846e52dc0b0c153d23972058031742ae4892454

build:
  number: 0
  script:
    # The default config.toml has target-cpu=native,
    # but we don't want that for portable CI builds.
    # Instead, use x86-64-v3 for x64, apple-m14 (=M1) for macos,
    # and the default otherwise.
    - mv .cargo/config-portable.toml .cargo/config.toml
    - cargo install --no-track --locked --verbose --root "${PREFIX}" --path .
  run_exports:
    - {{ pin_subpackage('sassy', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - sassy --help
    - sassy grep --help
    - sassy search --help
    - sassy crispr --help

about:
  home: https://github.com/ragnargrootkoerkamp/sassy
  license: MIT
  license_file: LICENSE
  summary: Fast approximate string searching

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - ragnargrootkoerkamp
    - rickbeeloo
