{% set name = "perl-getopt-long-descriptive" %}
{% set version = "0.117" %}
{% set sha256 = "18cba2392a0b7550bbc3d7c98c6fc5d81f6699d308e4a17e1a143ba4521005a3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Getopt-Long-Descriptive-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - make
  host:
    - perl
    - perl-test-warnings >=0.005
    - perl-cpan-meta-check
    - perl-carp
    - perl-cpan-meta-requirements
    - perl-sub-exporter
    - perl-params-validate
    - perl-extutils-makemaker
    - perl-test-fatal
    - perl-getopt-long
  run:
    - perl
    - perl-carp
    - perl-getopt-long
    - perl-sub-exporter
    - perl-params-validate

test:
  imports:
    - Getopt::Long::Descriptive
    - Getopt::Long::Descriptive::Opts
    - Getopt::Long::Descriptive::Usage

about:
  home: "https://github.com/rjbs/Getopt-Long-Descriptive"
  license: "Perl_5"
  summary: "Getopt::Long, but simpler and more powerful."
  dev_url: "https://github.com/rjbs/Getopt-Long-Descriptive"
  doc_url: "https://metacpan.org/pod/Getopt::Long::Descriptive"
