{% set name = "foldtree" %}
{% set version = "1.1.0rc2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url:  https://github.com/DessimozLab/fold_tree/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 04c721a12a68c2121932d9f7c5ceb8549278f9bef4e0d0b0201e0fe0aaeb4c1a
  
build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  run_exports:
    - {{ pin_subpackage("foldtree", max_pin="x.x") }}

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - click
    - snakemake-minimal

test:
  commands:
    - foldtree --help
    - foldtree --version

about:
  home: https://github.com/DessimozLab/fold_tree
  license: MIT
  license_file: LICENSE
  license_family: GPL3
  summary: "Foldtree creates phylogenetic trees from protein structures using Foldseek."
extra:
additional-platforms:
  - linux-aarch64
identifiers:
  - doi:10.1038/s41594-025-01649-8