{% set name = "longcalld" %}
{% set version = "0.0.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/yangao07/longcallD/releases/download/v{{ version }}/longcallD-v{{ version }}.tar.gz
  sha256: 4a2c2b217f89fa81d1402f4cbc791d8ead2a640835810cb0fa8c65e996fb2ed7

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name | lower, max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - autoconf
    - automake
    - libcurl
    - bzip2
    - liblzma 
    - xz
    - zlib
    - libdeflate
    - openssl  # [not osx]

test:
  commands:
    - longcallD call --version 2>&1 | grep {{ version }}

about:
  home: https://github.com/yangao07/longcallD
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'longcallD: local-haplotagging-based small and structural variant calling'
  dev_url: https://github.com/yangao07/longcallD

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
