{% set name = "perl-module-corelist" %}
{% set version = "5.20260220" %}
{% set sha256 = "51643766f15186bcb3542fadf1cbe416d53ee2800d71ba3b5467ab93f8520451" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/B/BI/BINGOS/Module-CoreList-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage('perl-module-corelist', max_pin="x") }}

requirements:
  build:
    - make
  host:
    - perl
    - perl-version
    - perl-extutils-makemaker
  run:
    - perl
    - perl-version

test:
  imports:
    - Module::CoreList
    - Module::CoreList::Utils

about:
  home: "https://metacpan.org/pod/Module::CoreList"
  license: "Perl_5"
  summary: 'What modules shipped with versions of perl.'
  doc_url: "https://metacpan.org/pod/Module::CoreList"
