{% set version = "0.1.7" %}
{% set sha256 = "4cffc3ca7628309bcfdd655f64ad167ade56b0ad8c47aae9493aa24f8d5ca0c9" %}

package:
  name: genomextract
  version: '{{ version }}'

source:
  url: https://github.com/kevinkarbstein/GenomeXtract/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-build-isolation --no-deps -vvv"
  run_exports:
    - {{ pin_subpackage("genomextract", max_pin="x.x") }}
  
requirements:
  build:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - biopython
    - pandas
    - requests
    - openpyxl
    - ncbi-datasets-cli ==18.9.0
    - raxml-ng ==1.2.2
    - iqtree ==3.0.1
    - mafft ==7.525
    - astral-tree ==5.7.8

test:
  commands:
    - findGenome --help
    - findClosestGenome --help
    - assembleOrgGenome --help
    - assembleOrgGenes --help

about:
  home: https://github.com/kevinkarbstein/GenomeXtract
  license: GPL-3.0-only
  license_file: LICENSE.txt
  summary: "GenomeXtract - A toolkit to easily find, compare, and assemble NCBI genomes."
