{% set name = "bohra" %}
{% set version = "3.4.0" %}
{% set sha256 = "79f6bac2796b7f984f8839e7434bcb6eb734ae8312e389e5bde7c384934726aa" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "{{ sha256 }}"

build:
  noarch: python
  number: 0
  entry_points:
    - bohra=bohra.bohra:cli
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv"
  run_exports:
    - {{ pin_subpackage('bohra', max_pin="x") }}

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.11 
    - nextflow
    - pytest
    - click
    - pandas
    - numpy
    - psutil
    - jinja2
    - csvtk

test:
  imports:
    - bohra
  commands:
    - bohra --version | grep -F '{{ version }}'
    - bohra --help

about:
  home: "https://github.com/MDU-PHL/bohra"
  license: "GPL-3.0-or-later"
  license_family: "GPL3"
  license_file: "LICENSE.txt"
  summary: "Pipeline for analysing Illumina data for microbiological public health."
  doc_url: "https://mdu-phl.github.io/bohra/"

extra:
  recipe-maintainers:
    - kristyhoran
    - tseemann
