{% set name = "atol-reference-data-lookups" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/TomHarrop/atol-reference-data-lookups/archive/refs/tags/{{ version }}.tar.gz
  sha256: 37e8b25aacaea7ecf693ab1e1905accdbd7e9477251abe20086bbe6ff329b61e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --no-cache-dir
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  entry_points:
    - atol-reference-data-lookups = atol_reference_data_lookups.atol_reference_data_lookups:main
    - get-remote-files = get_remote_files.get_remote_files:main
  run_exports:
    - {{ pin_subpackage('atol-reference-data-lookups', max_pin="x.x") }}

requirements:
  host:
    - pip
    - python >=3.13,<3.15
    - setuptools-scm
  run:
    - python >=3.13,<3.15
    - scikit-bio >=0.6.3
    - snakemake >=9.16.3,<10


test:
  commands:
    - "atol-reference-data-lookups --help | grep 'usage: atol-reference-data-lookups'"
    - "get-remote-files --help | grep 'usage: get-remote-files'"

about:
  home: "https://github.com/TomHarrop/atol-reference-data-lookups"
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: LICENSE
  summary: "Look up reference datasets by NCBI TaxId."
  dev_url: "https://github.com/TomHarrop/atol-reference-data-lookups"
