{% set name = "csubst" %}
{% set version = "1.8.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/kfuku52/csubst/archive/refs/tags/v{{ version }}.tar.gz
  sha256: eb568e33023db01e0516d373298f0b78d401be70109af5c532c2f6e588fa5304

build:
  number: 0
  skip: true  # [aarch64 or arm64]
  script:
    - export LDFLAGS="${LDFLAGS} -L${PREFIX}/lib"
    - export CPPFLAGS="${CPPFLAGS} -I${PREFIX}/include -I$(python -c 'import numpy; print(numpy.get_include())')"
    - sed -i.bak 's|find_packages|find_namespace_packages|' setup.py
    - rm -f *.bak
    - {{ PYTHON }} setup.py build_ext --inplace
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir --use-pep517 -vvv
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python >=3.10,<3.14
    - pip
    - cython
    - setuptools
    - numpy
  run:
    - python >=3.10,<3.14
    - ete4 >=4.3.0
    - numpy
    - scipy
    - pandas
    - matplotlib-base
    - iqtree >=2.0.0  # required
    - pyvolve         # optional: for csubst simulate
    - biopython       # optional: for csubst site --pdb besthit
    - pymol-open-source  # optional: for csubst site --pdb
    - mafft           # optional: for alignment (CLI)

test:
  commands:
    - csubst --help
  imports:
    - csubst

about:
  home: "https://github.com/kfuku52/csubst"
  license: "BSD-3-Clause"
  license_family: BSD
  summary: "Tool for analyzing combinatorial codon substitutions in DNA sequences."
  license_file: LICENSE
  dev_url: "https://github.com/kfuku52/csubst"
  doc_url: "https://github.com/kfuku52/csubst/blob/v{{ version }}/README.md"

extra:
  recipe-maintainers:
    - kfuku52
  identifiers:
    - doi:10.1038/s41559-022-01932-7
