{% set name = "snkmt" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/snkmt-{{ version }}.tar.gz
  sha256: a5876fda5c7a3507a3204d6630d88ccdab3acd04745cb8c3407a2587b614a1f6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --no-cache-dir
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  host:
    - python >=3.11,<4.0
    - hatchling
    - pip
  run:
    - textual >=3.1.1
    - typer >=0.15.3
    - sqlalchemy >=2.0.38
    - alembic >=1.16.1,<2.0.0
    - platformdirs >=4.3.8,<5.0.0
    - loguru >=0.7.3,<0.8.0
    - aiosqlite >=0.21.0,<0.22.0
    - beaupy >=3.0.0,<4.0.0

test:
  imports:
    - snkmt
  commands:
    - snkmt --help

about:
  home: "https://github.com/cademirch/snkmt"
  summary: "A TUI for monitoring Snakemake workflows in real-time."
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: "https://github.com/cademirch/snkmt"

extra:
  recipe-maintainers:
    - fgvieira
