{% set name = "collectl" %}
{% set version = "4.3.20.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/sharkcz/collectl/archive/refs/tags/{{ version }}.tar.gz
  sha256: f917146c0ebea0e643acf738b21943e5abc16b786a7930352a825dfa031055de
  patches:
    - 0001-INSTALL.patch
    - usrenvbin.patch

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  host:
    - perl
    - zlib
  run:
    - perl

test:
  commands:
    - collectl --help

about:
  home: "https://github.com/sharkcz/collectl"
  license: "Artistic License"
  summary: "Collectl is a light-weight performance monitoring tool capable of reporting interactively as well as logging to disk."
  doc_url: "https://collectl.sourceforge.net"
  dev_url: "https://github.com/sharkcz/collectl"
