{% set name = "py_nucflag" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: db9dc7133bbc6da7301b369eb7b0646901e6303545f873c5dbc03133f49ab568

build:
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  number: 0
  skip: True  # [osx]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler("rust") }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.8,<2.0
    - pip
  run:
    - python
    - polars

test:
  imports:
    - py_nucflag
  commands:
    - pip check
  requires:
    - pip

about:
  license: MIT
  license_file: py/LICENSE
  summary: Library to call misassemblies in genome assemblies from long-read alignments.
  home: https://github.com/logsdon-lab/rs-nucflag

extra:
  recipe-maintainers:
    - koisland
