{% set version = "3.0.6" %}
{% set name = "vamos" %}

package:
  name: vamos
  version: {{ version }}

source:
  url: https://github.com/ChaissonLab/vamos/archive/refs/tags/vamos-v{{ version }}.tar.gz
  sha256: 227889bd61a5004b0419daaf37d15c5706192fc8c00846a5a73c3e36500a2646
  patches:
    - vamos-aarch64.patch  # [arm64 or aarch64]

build:
  number: 0
  skip: true  # [aarch64 or arm64]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - make
    - cmake <3.29
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
    - htslib
    - boost-cpp
  run:
    - htslib
    
test:
  commands:
    - vamos | grep 'Usage'

about:
  home: "https://github.com/ChaissonLab/vamos"
  license: "GPL-2.0-only"
  license_family: GPL
  license_file: "LICENSE.txt"
  summary: 'VNTR annotation using efficient motif selection.'
  dev_url: "https://github.com/ChaissonLab/vamos"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
