{% set name = "Kalamari" %}
{% set version = "5.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lskatz/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1223fde7df9b9933936dc02ea38d87aa420fce27ae3d2ce92ddfffab8ede714c

build:
  number: 1
  noarch: generic
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x") }}

requirements:
  host:
    - perl
    - perl-module-build
    - entrez-direct
  run:
    - perl
    - perl-module-build
    - entrez-direct

test:
  commands:
    - downloadKalamari.pl --help

about:
  home: "https://github.com/lskatz/kalamari"
  summary: "A curated database of completed assemblies with taxonomy IDs"
  description: |
    Kalamari is a curated database of assemblies and taxonomies.
    These assemblies are curated mainly for foodborne bacteria but have other taxa
    such as SARS-CoV-2 and Crytposporidium.
    Taxonomy has been modified from NCBI Taxonomy and has been minimalized to
    just what is needed here.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: "https://github.com/lskatz/Kalamari/blob/master/README.md"
  dev_url: "https://github.com/lskatz/Kalamari"
  identifiers:
    - doi: 10.1128/mra.00963-24

extra:
  recipe-maintainers:
    - lskatz
    - rpetit3
