{% set name = "scarap" %}
{% set version = "1.0.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scarap-{{ version }}.tar.gz
  sha256: e7623c791815f14cb0a6b6fa4d71b2a9fc389fd9a6281e1c41d40c2f2ab428a7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  host:
    - python >=3.8,<3.13
    - setuptools
    - setuptools-scm
    - pip
  
  run:
    - python >=3.8,<3.13
    - biopython >=1.79,<2
    - ete3 >=3.1,<4
    - numpy >=1.18,<3
    - scipy >=1.4,<2
    - pandas >=1.3,<3
    - mafft >=7.407
    - mmseqs2 >=11

test:
  imports:
    - scarap
  commands:
    - pip check
    - scarap --help
  requires:
    - pip 

about:
  home: https://pypi.org/project/{{ name }}
  dev_url: https://github.com/swittouck/scarap
  summary: A toolkit for prokaryotic comparative genomics
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TheOafidian
    - swittouck
  identifiers:
    - doi:10.1093/bioinformatics/btae735
