{% set name = "alpharaw" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MannLabs/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3b184f4be58d382b9d9cec905494d27b9f6aab6e584c405c152c000e049a74d9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --no-cache-dir
  number: 0
  run_exports:
    - {{ pin_subpackage('alpharaw', max_pin="x.x") }}

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - pythonnet
    - h5py
    - numba
    - pandas
    - numpy
    - pyteomics
    - lxml
    - owlready2
    - alphabase >=1.5.0
    - alphatims

test:
  imports:
    - alpharaw
  commands:
    - pip check
    - alpharaw --help
  requires:
    - pip

about:
  home: https://github.com/MannLabs/alpharaw
  summary: An open-source Python package to unify raw MS data access and storage
  description: |
    AlphaRaw provides unified access to raw mass spectrometry data from
    various instrument vendors, converting them to a standardized HDF5
    format for downstream analysis in the AlphaPept ecosystem.
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  dev_url: https://github.com/MannLabs/alpharaw

extra:
  recipe-maintainers:
    - jonasscheid
