{% set repo = "repermulize" %}
{% set name = "repermulize" %}
{% set version = "1.0" %}
{% set sha256 = "5d75a179cfc78f852e12da2ab4d188cbdafb82fc64b18a5c390db357f8be048f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/pbradleylab/{{ repo }}/archive/refs/tags/v1.0.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
  run_exports:
    - {{ pin_subpackage(name, max_pin = "x.x") }}

requirements:
  host:
    - r-base >=4.2,<4.3.0a0
    - r-phylolm =2.6.2
    - bioconductor-ggtree =3.6.0
    - bioconductor-biomformat =1.26.0
    - bioconductor-qvalue =2.30.0
    - r-plotly <=4.10.4
    - r-kableextra =1.4.0
    - r-dt =0.33
    - r-settings =0.2.7
    - r-readr =2.1.4
    - r-stringr =1.5.0
    - r-tidyr =1.3.0
    - r-tibble =3.2.1
    - r-purrr =1.0.1
    - r-matrix =1.5_4.1
    - r-extradistr =1.9.1
    - r-castor =1.7.10
    - r-phylolm =2.6.2
    - r-pbapply =1.7_0
    - r-forcats =1.0.0
    - r-seqinr =4.2_30
    - r-ashr =2.2_54
    - bioconductor-s4vectors =0.36.0
  run:
    - r-base >=4.2,<4.3.0a0
    - r-phylolm =2.6.2
    - bioconductor-ggtree =3.6.0
    - bioconductor-biomformat =1.26.0
    - bioconductor-qvalue =2.30.0
    - r-plotly <=4.10.4
    - r-kableextra =1.4.0
    - r-dt =0.33
    - r-settings =0.2.7
    - r-readr =2.1.4
    - r-stringr =1.5.0
    - r-tidyr =1.3.0
    - r-tibble =3.2.1
    - r-purrr =1.0.1
    - r-matrix =1.5_4.1
    - r-extradistr =1.9.1
    - r-castor =1.7.10
    - r-phylolm =2.6.2
    - r-pbapply =1.7_0
    - r-forcats =1.0.0
    - r-seqinr =4.2_30
    - r-ashr =2.2_54
    - bioconductor-s4vectors =0.36.0

test:
  commands:
    - '$R -e "library(repermulize)"'

about:
  home: "https://github.com/pbradleylab/phylogenize"
  dev_url: "https://github.com/pbradleylab/phylogenize"
  license: MIT
  license_family: MIT
  summary: "Repermulize contains functions to perform gene-to-phenotype tests with permulation."

extra:
  recipe-maintainers:
    - kekananen
