{% set name = "quantms-utils" %}
{% set version = "0.0.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quantms_utils-{{ version }}.tar.gz
  sha256: cc178d55290b5afcddb93a8c1c3079cc4906610bfb53c4f501bf24915136d7f6

build:
  entry_points:
    - quantmsutilsc=quantmsutils.quantmsutilsc:main
  noarch: python
  run_exports:
    - {{ pin_subpackage('quantms-utils', max_pin="x.x") }}
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv"
  number: 0

requirements:
  host:
    - python
    - pip
    - poetry-core
    - setuptools <78
  run:
    - python >=3.9,<3.13
    - setuptools <78
    - click
    - sdrf-pipelines >=0.0.33,<0.1.0
    - pyopenms >=3.3.0
    - pandas
    - numpy
    - pyarrow >=16.1.0
    - scipy
test:
  requires:
    - setuptools <78
  imports:
    - quantmsutils
  commands:
    - quantmsutilsc --help

about:
  home: "https://www.github.com/bigbio/quantms-utils"
  summary: "Python package with scripts and helpers for the quantms workflow."
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: "https://www.github.com/bigbio/quantms-utils"
  doc_url: "https://quantms.org/home"

extra:
  recipe-maintainers:
    - ypriverol
