{% set name = "perl-lwp-protocol-https" %}
{% set version = "6.15" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/LWP-Protocol-https-{{ version }}.tar.gz
  sha256: 44eec2da147ba0511090871b0ca82f69794376bc31e8c76d1040961ba57f59b8

build:
  number: 0
  noarch: generic
  run_exports:
      - {{ pin_subpackage('perl-lwp-protocol-https', max_pin="x") }}

requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
    - perl-file-spec
    - perl-file-temp
    - perl-io-socket-ssl
    - perl-mozilla-ca
    - perl-net-http
    - perl-test-requiresinternet
    - perl-test-simple
  run:
    - perl
    - perl-io-socket-ssl
    - perl-mozilla-ca
    - perl-net-http
    - perl-test-requiresinternet

test:

about:
  home: "https://metacpan.org/pod/LWP::Protocol::https"
  license: "Perl_5"
  summary: "Provide https support for LWP::UserAgent."
  doc_url: "https://metacpan.org/pod/LWP::Protocol::https"

extra:
  skip-lints:
    - missing_tests
