{% set version = "1.1.2" %}

package:
  name: lodei
  version: {{version}}

source:
  url: https://github.com/rna-editing1/lodei/archive/refs/tags/lodei_v{{version}}.tar.gz
  sha256: 6a9b6a6df331f969a74a0ea83d97997d5d4ce20f39050823985478ab6e98ea34 

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps --no-build-isolation -vvv
  run_exports:
    - {{ pin_subpackage('lodei', max_pin="x") }}

requirements:
  host:
    - python
    - pip
    - setuptools >=67.6
    - wheel
  run:
    - python >=3.10,<3.11
    - pysamstats 
    - pandas
    - matplotlib-base
    - samtools

test:
  commands:
    - lodei --help

about:
  home: https://github.com/rna-editing1/lodei
  license: GPL-3.0-or-later
  license_file: LICENSE
  doi: 10.1038/s41467-024-53298-y
  summary: Analyze differentially edited A-to-I regions in two sets of RNA-seq samples.
  details: |
    LoDEI - the local differential editing index - offers a collection of programs 
    to detect and analyze differential RNA editing like A-to-I editing in two sets of RNA-seq samples.
