package:
  name: duphist
  version: "1.1.0"

source:
  url: https://github.com/minjeongjj/DupHIST/archive/refs/tags/v1.1.0.tar.gz
  sha256: 1a6aefbc65e978c887454db6ea0f66abebab89340e2ae677fb2e997bf97de440

build:
  noarch: generic
  number: 1
  script: |
    mkdir -p $PREFIX/bin/scripts
    cp -r scripts/* $PREFIX/bin/scripts/
    cp duphist $PREFIX/bin/
    chmod +x $PREFIX/bin/duphist
  run_exports:
    - {{ pin_subpackage("duphist", max_pin="x") }}

requirements:
  run:
    - perl
    - perl-config-tiny
    - perl-data-dumper
    - perl-statistics-r
    - r-base
    - r-cluster
    - r-desctools
    - r-nbclust
    - r-foreach
    - r-doparallel
    - r-tictoc
    - r-agricolae
    - r-ape
    - prank
    - kakscalculator2
    - mafft
    - fasttree
    - iqtree

test:
  commands:
    - duphist --help || true

about:
  home: https://github.com/minjeongjj/DupHIST
  license: MIT
  summary: "DupHIST: Duplication History Inference with Substitution-integrated Topology"
  license_file: LICENSE
