{% set name = "nwkit" %}
{% set version = "0.21.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/kfuku52/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 16a7026eec1e29fc65fc96932ccc6e8dd83733e644d388920ede7e4ff7c3bfca

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-build-isolation --no-deps -vv"
  run_exports:
    - {{ pin_subpackage("nwkit", max_pin="x.x") }}

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.9
    - ete4 >=4.3.0
    - biopython
    - pandas
    - requests
    - numpy

test:
  commands:
    - nwkit --help
  imports:
    - nwkit

about:
  home: "https://github.com/kfuku52/nwkit"
  license: "BSD-3-Clause"
  license_file: LICENSE
  summary: "Tools for processing newick trees"

extra:
  recipe-maintainers:
    - kfuku52
