{% set name = "perl-unicode-utf8" %}
{% set version = "0.66" %}
{% set sha256 = "86874238fc4ff5c4931edb88ed1dcd50115c51902573f1807b27d9b13af5c0f0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/C/CH/CHANSEN/Unicode-UTF8-0.66.tar.gz
  sha256: {{ sha256 }}

build:
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}
  number: 0

requirements:
  build:
    - make
    - {{ compiler('cxx') }}

  host:
    - perl
    - perl-test-fatal
    - perl-exporter
    - perl-encode
    - perl-extutils-makemaker
    - perl-carp
  run:
    - perl
    - perl-carp
    - perl-exporter

test:
  imports:
    - Unicode::UTF8

about:
  home: http://metacpan.org/pod/Unicode::UTF8
  license: perl_5
  summary: 'Encoding and decoding of UTF-8 encoding form'

extra:
  # osx-arm64 is erroring due to missing perl-encode in conda forge
  additional-platforms:
    - linux-aarch64
