{% set version = "0.16.0" %}

package:
  name: snakedeploy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/snakedeploy/snakedeploy-{{ version }}.tar.gz
  sha256: a959775ced480b3de74bb70cbee3fde0eb813a53b6635a3a74ad5501c36e5d52

build:
  number: 0
  noarch: python
  entry_points:
    - snakedeploy=snakedeploy.client:main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir --use-pep517 -vvv
  run_exports:
    - {{ pin_subpackage('snakedeploy', max_pin="x.x") }}

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.11,<3.13
    - hatchling
  run:
    - python >=3.11,<3.13
    - setuptools
    - jinja2 >=3.1.6,<4
    - packaging >=25.0,<26
    - pandas >=2.3.1,<3
    - pygithub >=2.6.1,<3
    - pyyaml >=6.0.2,<7
    - requests >=2.32.4,<3
    - reretry >=0.11.8,<1
    - toml >=0.10.2,<1

test:
  imports:
    - snakedeploy
  commands:
    - snakedeploy --help

about:
  home: https://github.com/snakemake/snakedeploy
  summary: "Helper for deploying published Snakemake pipelines."
  license: MPL-2.0
  license_file: LICENSE
  dev_url: https://github.com/snakemake/snakedeploy

extra:
  recipe-maintainers:
    - johanneskoester
