{% set name = "ngmaster" %}
{% set version = "1.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/MDU-PHL/ngmaster/archive/refs/tags/v{{ version }}.tar.gz"
  sha256: f186f0d642a4d8830ec69eafdf4cb5b04dce749aa01bbe0d6d523b9ce238687e

build:
  number: 1
  noarch: python
  entry_points:
    - ngmaster=ngmaster.run_ngmaster:main
  script: "{{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --no-cache-dir"
  run_exports:
    - {{ pin_subpackage('ngmaster', max_pin="x") }}

requirements:
  host:
    - python >=3.12
    - pip
    - setuptools
  run:
    - python >=3.12
    - biopython
    - mlst
    - requests

test:
  imports:
    - ngmaster
  commands:
    - ngmaster --help
    - ngmaster --test

about:
  home: "https://github.com/MDU-PHL/ngmaster"
  license: "GPL-3.0-only"
  license_family: "GPL3"
  license_file: "LICENSE"
  summary: "In silico multi-antigen sequence typing for N. gonorrhoeae (NG-MAST and NG-STAR)."
  doc_url: "https://github.com/MDU-PHL/ngmaster/blob/master/README.md"
  dev_url: "https://github.com/MDU-PHL/ngmaster"

extra:
  recipe-maintainers:
    - stroehleina
    - kristyhoran
