{% set version = "0.6.11" %}
{% set sha256 = "f1a1275c0c2d42ae27fa02c59b0d02ff1053cfbfe29c9d28a026392dd17bed37" %}

package:
  name: trim-galore
  version: '{{version}}'

source:
  url: https://github.com/FelixKrueger/TrimGalore/archive/{{version}}.zip
  sha256: '{{sha256}}'

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage("trim-galore", max_pin="x") }}

requirements:
  build:
  run:
    - perl
    - fastqc
    - cutadapt ==5.2

test:
  commands:
    - trim_galore --help | grep trim_galore > /dev/null

about:
  home: https://github.com/FelixKrueger/TrimGalore
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Trim Galore! is a wrapper script to automate quality and adapter trimming
    as well as quality control
  dev_url: https://github.com/FelixKrueger/TrimGalore

extra:
  identifiers:
    - usegalaxy-eu:trim_galore
