{% set version = "0.7.1" %}
{% set name = "salti" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/sam-sims/{{ name }}/archive/{{ name }}-{{ version }}.tar.gz
  sha256: f7f33c216fedcc2c9eaa7ead5c34e7cc2c049d5edf71a9dd03eb356d4f2b425c

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('salti', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - make

test:
  commands:
    - salti --version

about:
  home: https://github.com/Sam-Sims/salti
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: A modern multiple sequence alignment browser - built for the terminal. 

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - sam-sims
    