{% set version = "9.0.3" %}
{% set sha256 = "b1a0df3685f1eed59e0080fe77683f8580afe3e403e3e344e34ffaa67f04e86c" %}

package:
  name: ena-webin-cli
  version: {{ version }}

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage('ena-webin-cli', max_pin="x") }}

source:
    url: https://github.com/enasequence/webin-cli/releases/download/{{ version }}/webin-cli-{{ version }}.jar
    sha256: {{ sha256 }}

requirements:
  run:
    - openjdk >=17
    - python

test:
  commands:
    - ena-webin-cli -version

about:
  home: https://github.com/enasequence/webin-cli
  license: Apache-2.0
  summary: Data submissions to ENA can be made using the Webin command line submission interface (Webin-CLI).
