{% set version = "1.10" %}

package:
  name: hybran
  version: '{{ version }}'

source:
  url: https://gitlab.com/LPCDRP/hybran/-/archive/{{ version }}/hybran-{{ version }}.tar.gz
  sha256: '5ce08f60ac7c39ab4e3416ae0de20544c85bc52e4e2788cbb6d35caa0438cfd7'

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  run_exports:
    - {{ pin_subpackage('hybran', max_pin='x') }}

requirements:
  host:
    - python >=3.12
    - pip
    - setuptools <81
  run:
    - biopython >=1.80
    - blast
    - cd-hit
    - diamond
    - dill
    - eggnog-mapper
    - emboss
    - entrez-direct
    - frozendict
    - intervaltree
    - mcl
    - multiprocess
    - networkx
    - prokka >=1.14
    - python >=3.12
    - ratt
    - tbl2asn-forever

test:
  commands:
    - hybran --help

about:
  home: https://lpcdrp.gitlab.io/hybran
  dev_url: https://gitlab.com/LPCDRP/hybran
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Comparative prokaryotic genome annotation
