{% set name = "gfftk" %}
{% set version = "26.2.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gfftk-{{ version }}.tar.gz
  sha256: 7dfc3a215cee322282f7ea271ffbcd859bd493ff3494232f03335e64dec6fa61

build:
  number: 0
  noarch: python
  entry_points:
    - gfftk = gfftk.__main__:main
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --no-cache-dir
  run_exports:
    - {{ pin_subpackage('gfftk', max_pin="x") }}

requirements:
  host:
    - python >=3.6
    - pip
    - hatchling
  run:
    - python >=3.6
    - natsort
    - numpy
    - table2asn
    - requests
    - gb-io >=0.3.2

test:
  imports:
    - gfftk
  commands:
    - gfftk --help

about:
  home: https://github.com/nextgenusfs/gfftk
  summary: 'GFFtk: genome annotation GFF3 tool kit'
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.md
  dev_url: https://github.com/nextgenusfs/gfftk

extra:
  recipe-maintainers:
    - nextgenusfs
