{% set version = "1.2.0" %}

package:
  name: mist_typing
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mist_typing/mist_typing-{{ version }}.tar.gz
  sha256: d459d9045ca9c7167734266d828d9f4288bca7e778ba70e5c5c2136d1f7f6bb0

build:
  noarch: python
  number: 0
  entry_points:
    - mist=mist.scripts.cli:cli
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv"
  run_exports:
    - {{ pin_subpackage('mist_typing', max_pin="x") }}

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >61
  run:
    - python >=3.10
    - biopython
    - bs4
    - cd-hit >=4.6.8
    - click
    - furl
    - minimap2 >=2.26
    - mummer4
    - pandas >2
    - pyyaml
    - rauth
    - requests
    - scipy

about:
  home: https://github.com/BioinformaticsPlatformWIV-ISP/MiST
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: MiST is a rapid, accurate and flexible (core-genome) multi-locus sequence typing (MLST) allele caller.
  dev_url: https://github.com/BioinformaticsPlatformWIV-ISP/MiST

test:
  imports:
    - mist
  commands:
    - mist --version
    - mist --help

extra:
  recipe-maintainers:
    - BertBog
