{% set name = "genomesyn2" %}
{% set version = "1.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/banzhou59/GenomeSyn2/releases/download/v{{ version }}/GenomeSyn2-{{ version }}.tar.gz
  sha256: b3e89561849aed5de43af577ff30ffa666e4a6c6caec5f03db9943d19c2cf5ac

build:
  run_exports:
    - {{ pin_subpackage("genomesyn2", max_pin=None) }}
  number: 0
  noarch: generic
  script: |
    mkdir -p $PREFIX/bin
    cp -r bin/* $PREFIX/bin/

requirements:
  run:
    - perl >=5.32
    - perl-bioperl-core
    - perl-svg
    - python >=3.8
    - cairosvg
    - mummer4
    - minimap2
    - gffread
    - seqkit
    - blast
    - diamond
    - mmseqs2

test:
  commands:
    - GenomeSyn2 --help

about:
  home: https://github.com/banzhou59/GenomeSyn2
  license: MIT
  license_file: LICENSE
  summary: "A Comparative Genomics Framework Integrating Synteny Visualization"
  description: |
    GenomeSyn2 is a flexible and high-performance framework for comparative
    genomics visualization, synteny construction, and multi-genome feature
    analysis. It supports multiple alignment engines (MUMmer, minimap2, BLASTp,
    Diamond, MMseqs2) and provides rich downstream visualization modules.

extra:
  recipe-maintainers:
    - banzhou59