{% set name = "recentrifuge" %}
{% set version = "2.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation --no-cache-dir . -vvv
  run_exports:
    - {{ pin_subpackage('recentrifuge', max_pin="x") }}

source:
  url: https://github.com/khyox/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2e87f64d5aa4daa15b428dae9bddc3de7ad99c79521516fb2fedf80a5892aa9b

requirements:
  host:
    - python >=3.12
    - pip
    - setuptools >=75.0.0
  run:
    - python >=3.12
    - biopython ==1.84
    - numpy >=2.3.4
    - matplotlib-base >=3.3.4
    - openpyxl >=3.1.2
    - pandas >=2.3.3

test:
  commands:
    - rcf --version

about:
  home: https://github.com/khyox/recentrifuge
  license: 'AGPL-3.0-or-later'
  license_family: AGPL
  license_file: LICENSE.txt
  summary: 'Robust comparative analysis and contamination removal for metagenomics.'
  doc_url: https://github.com/khyox/recentrifuge/wiki
  dev_url: https://github.com/khyox/recentrifuge

extra:
  recipe-maintainers:
    - thanhleviet
    - khyox
  identifiers:
    - doi:10.1371/journal.pcbi.1006967
    - biotools:Recentrifuge
    - usegalaxy-eu:recentrifuge
