{% set name = "amalgkit" %}
{% set version = "0.14.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/kfuku52/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: dc180688258c6112dfca02cfca2cf66b11fc8db74f2ef112990a18a3357ac503

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-build-isolation -vv"
  run_exports:
    - {{ pin_subpackage("amalgkit", max_pin="x.x") }}

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - wheel

  run:
    - python >={{ python_min }}
    - biopython
    - numpy
    - pandas
    - ete4
    # Additional dependencies for amalgkit
    - seqkit
    - sra-tools
    - fastp
    - kallisto
    - r-base
    - bioconductor-edger
    - r-ggplot2
    - bioconductor-sva
    - r-rtsne
    # Optional runtime dependencies:
    # - busco, compleasm (required only for `amalgkit busco`)
    # - bioconductor-ruvseq (required only for `amalgkit curate --batch_effect_alg ruvseq`)

test:
  commands:
    - amalgkit --help
  imports:
    - amalgkit

about:
  home: "https://github.com/kfuku52/amalgkit"
  license: "MIT"
  license_file: LICENSE
  summary: "Tools for transcriptome amalgamation"

extra:
  recipe-maintainers:
    - kfuku52
