{% set name = "perl-perl-version" %}
{% set version = "1.019" %}
{% set sha256 = "a45a6e3f0d92fcb33214248a52d443e2b8ffd5fffdaf09b54cb7cb9dff588004" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/B/BR/BRIANDFOY/Perl-Version-1.019.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - make
  host:
    - perl
    - perl-pod-usage
    - perl-file-slurp-tiny
    - perl-extutils-makemaker
    - perl-getopt-long
    - perl-data-dumper
    - perl-carp

  run:
    - perl
    - perl-carp
    - perl-file-slurp-tiny
    - perl-getopt-long
    - perl-data-dumper
    - perl-pod-usage

test:
  imports:
    - Perl::Version

about:
  home: http://metacpan.org/pod/Perl::Version
  license: perl_5
  summary: 'Parse and manipulate Perl version strings'
