{% set name = "rnastructure" %}
{% set version = "6.5" %}
{% set sha256 = "2e6064aebe568549beca149df0e7a3d977ddf12b9907eea01ae7b81984c8ad45" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  sha256: {{ sha256 }}
  url: http://rna.urmc.rochester.edu/Releases/{{ version }}/RNAstructureSource.tgz

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name | lower, max_pin="x.x") }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  run:
    - llvm-openmp  # [osx]

# In  version 6.0, several commands are returning exit code 1 when called with
# the -h option. Therefore, changed the modules that are tested.
test:
  commands:
    - bifold -h || true
    - fold -h || true

about:
  home: http://rna.urmc.rochester.edu/RNAstructure.html
  license: GPL-2.0-only
  license_family: GPL
  license_file: gpl.txt
  summary: 'RNAstructure is a complete package for RNA and DNA secondary structure  prediction
    and analysis. It includes algorithms for   secondary structure  prediction, including
    facility to predict base pairing probabilities. It  also can be used to predict
    bimolecular structures and can predict the  equilibrium binding affinity of an
    oligonucleotide to a structured RNA  target. This is useful for siRNA design.
    It can also predict secondary  structures common to two, unaligned sequences,
    which is much more accurate  than single sequence secondary structure prediction.
    Finally, RNAstructure  can take a number of different types of experiment mapping
    data to constrain  or restrain structure prediction. These include chemical mapping,
    enzymatic  mapping, NMR, and SHAPE data.'