{% set name = "samshee" %}
{% set version = "0.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/43/41/a87daadcf1c9c4a7281853d36ad7c7da77fcafe0335ea5541b9359a52397/samshee-0.2.13.tar.gz
  sha256: 0a9289e87230ded88379ab3b8d89b43b94162901cc47ea2e0c87894cd3f1c3c1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  run_exports:
    - {{ pin_subpackage('samshee', max_pin="x.x.x") }}

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - pip
  run:
    - python >=3.9
    - jsonschema >=4.19
    - requests >=2.31.0

test:
  imports:
    - samshee
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lit-regensburg/samshee
  summary: A schema-agnostic parser and writer for illumina sample sheets v2.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - j4cko
    - nschcolnicov
