{% set name = "razers3" %}
{% set razer_version = "3.5.12" %}
{% set seqan_version = "2.5.2" %}

package:
  name: {{ name }}
  version: {{ razer_version }}

source:
  url: https://github.com/seqan/seqan/archive/refs/tags/seqan-v{{ seqan_version }}.tar.gz
  sha256: 4974dfbf802a3e3b63c3e34855e331a7545f8def1c9f4a4dc6712c4d3812179e

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('razers3', max_pin="x") }}

requirements:
  build:
    - ninja
    - {{ compiler('cxx') }}
    - cmake
  host:
    - zlib
    - bzip2
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
  run:
    - libgomp  # [linux]
    - llvm-openmp  # [osx]

test:
  commands:
    - razers3 --help

about:
  home: "https://www.seqan.de/apps/razers3.html"
  license: "GPL-3.0-only"
  license_file: LICENSE
  license_family: GPL3
  summary: "RazerS 3 - Faster, fully sensitive read mapping."
  dev_url: "https://github.com/seqan/seqan/tree/main/apps/razers3"
  doc_url: "https://www.seqan.de/apps/razers3.html"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
