{% set name = "mosdepth" %}
{% set version = "0.3.13" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/brentp/mosdepth/archive/refs/tags/v{{ version }}.tar.gz
  sha256: db120c279577c232305e51fbd48704ab75f235615e5df2a8eb6a327be5d42aca

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('mosdepth', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - nim  # [not arm64]
    - coreutils
  host:
    - htslib
    - curl
    - tar
    - bzip2
    - xz
    - zlib
  run:
    - htslib

test:
  commands:
    - mosdepth -h

about:
  home: "https://github.com/brentp/mosdepth"
  dev_url: "https://github.com/brentp/mosdepth"
  doc_url: "https://github.com/brentp/mosdepth/blob/v{{ version }}/README.md"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Fast BAM/CRAM depth calculation for WGS, exome, or targeted sequencing."

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - doi:10.1093/bioinformatics/btx699
    - biotools:mosdepth
    - usegalaxy-eu:mosdepth
