{% set name = "fastmd5" %}
{% set version = "1.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/moold/fastMD5/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 04dd281591ca6e6de3cd57aca4a7b9315b85af72f7452cfef0f45a3756795bed

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('fastmd5', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - pkg-config        # rust crates often need this
    - make
    - cmake
    - pkg-config
    - clangdev
    - llvmlite

test:
  commands:
    - fastmd5 --help

about:
  home: "https://github.com/moold/fastMD5"
  license: MIT
  license_file: LICENSE
  summary: "Fast command-line tool to compute and verify MD5 checksums"
  dev_url: "https://github.com/moold/fastMD5"
  doc_url: "https://github.com/moold/fastMD5/blob/main/README.md"

extra:
  recipe-maintainers:
    - moold
  additional-platforms:
    - linux-aarch64
    - osx-arm64
