{% set version = "0.4.8" %}

package:
  name: atlas-fastq-provider
  version: {{ version }}

source:
  url: https://github.com/ebi-gene-expression-group/atlas-fastq-provider/archive/v{{ version }}.tar.gz
  sha256: db5ad4a435d41b5516f330d909d09e5085e6e839eb119206e5a2741ea7bd2011

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage("atlas-fastq-provider", max_pin="x.x") }}

requirements:
  build:
  host:
  run:
    - bash
    - wget
    - coreutils
    - grep
    - sra-tools =2.11.0
    - fastq_utils

test:
  commands:
    - fetchFastq.sh -h

about:
  home: https://github.com/ebi-gene-expression-group/atlas-fastq-provider
  license: GPL-3
  summary: A package to provide FASTQs via download or file system linking.
  license_family: GPL3

extra:
  recipe-maintainers:
    - pmb59
    - anilthanki
    - pinin4fjords
