{% set name = "bowtie2" %}
{% set version = "2.5.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/BenLangmead/bowtie2/archive/v{{ version }}.tar.gz
  sha256: e38d1833ec235ca27fa57589d32d897c9addf87085b7cb7bc978662954662da2

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - git
  host:
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - zlib
    - zstd
  run:
    - python
    - perl
    - llvm-openmp  # [osx]
    - libgomp  # [linux]

test:
  commands:
    - bowtie2 --help
    - bowtie2 --version
    # test if bowtie2 reports its version
    - bowtie2 --version | grep -q "bowtie2-align-s version [0-9]"  # [linux]
    - bowtie2-align-l --help
    - bowtie2-align-s --help
    - bowtie2-build --help
    - bowtie2-build-l --help
    - bowtie2-build-s --help
    - bowtie2-inspect --help
    - bowtie2-inspect-l --help
    - bowtie2-inspect-s --help

about:
  home: "https://bowtie-bio.sourceforge.net/bowtie2/index.shtml"
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: LICENSE
  summary: "A fast and sensitive gapped read aligner."
  dev_url: "https://github.com/BenLangmead/bowtie2"
  doc_url: "https://github.com/BenLangmead/bowtie2/blob/v{{ version }}/README.md"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - biotools:bowtie2
    - doi:10.1038/nmeth.1923
    - debian:bowtie2
    - usegalaxy-eu:bowtie2
