{% set name = "fgumi" %}
{% set version = "0.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/fulcrumgenomics/{{ name }}/archive/{{ name }}-v{{ version }}.tar.gz
  sha256: 24c84a1fb6dd735a85548654106508528f5b42b408cdbc3f8fc6dc4046f49687

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('fgumi', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  run:
    - r-base
    - r-ggplot2
    - r-scales

test:
  commands:
    - fgumi --help

about:
  home: "https://github.com/fulcrumgenomics/{{ name }}"
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: "High-performance tools for UMI-tagged sequencing data."
  dev_url: "https://github.com/fulcrumgenomics/{{ name }}"
  doc_url: "https://github.com/fulcrumgenomics/{{ name }}/blob/{{ name }}-v{{ version }}/README.md"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - nh13
    - tfenne
