{% set name = "toulligqc" %}
{% set version = "2.8.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c62647cb7829b26703ba1f5cf681fa0c0cca315595219078bb811e082e90e882

build:
  number: 0
  entry_points:
    - toulligqc=toulligqc.toulligqc:main
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv"
  noarch: python
  run_exports:
    - {{ pin_subpackage('toulligqc', max_pin="x") }}

requirements:
  host:
    - python >=3.11
    - pip
    - setuptools
    - wheel
    - hatchling
  run:
    - h5py >=3.10.0
    - matplotlib-base >=3.6.3
    - numpy >=1.26.4
    - scipy >=1.11.4
    - pandas >=2.1.4
    - plotly >=5.15.0,<6.0.0
    - pysam >=0.22.0
    - python >=3.11
    - scikit-learn >=1.4.1
    - tqdm >=4.66.2
    - pod5 >=0.3.15
    #- ezcharts ==0.7.6

test:
  imports:
    - toulligqc
  commands:
    - toulligqc --help

about:
  home: "https://github.com/GenomicParisCentre/toulligQC"
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: "LICENSE.txt"
  summary: "A post sequencing QC tool for Oxford Nanopore sequencers."
  dev_url: "https://github.com/GenomicParisCentre/toulligQC"
  doc_url: "https://github.com/GenomiqueENS/toulligQC/blob/v{{ version }}/README.md"

extra:
  identifiers:
    - biotools:ToulligQC
