{% set name = "cgatcore" %}
{% set version = "0.6.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cec501d7d35dce17a984d83b55cb56e834b45a4bcccfa3579171f0b3be2565b6

build:
  number: 0
  noarch: python
  run_exports:
    - {{ pin_subpackage('cgatcore', max_pin="x.x") }}
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    # Python deps
    - python >=3
    - pip
    - setuptools
    - gevent
    - pandas
    - drmaa
    - pyyaml >=5.1
    - ruffus
    - six
    - sqlalchemy
    # Misc deps
    - coreutils
    - nomkl
    - time

  run:
    # Python deps
    - python >=3
    - gevent
    - pandas
    - drmaa
    - pyyaml >=5.1
    - ruffus
    - six
    - sqlalchemy
    # Misc deps
    - coreutils
    - nomkl
    - time
    - boto3
    - google-cloud-storage
    - google-cloud-sdk
    - ftputil
    - pysftp
    - apsw

test:
  imports:
    - cgatcore
    - cgatcore.iotools
    - cgatcore.experiment
    - cgatcore.pipeline
    - cgatcore.database
    - cgatcore.tables

about:
  home: https://github.com/cgat-developers/cgat-core
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'CGAT : the Computational Genomics Analysis Toolkit'

extra:
  recipe-maintainers:
    - sebastian-luna-valero
    - AndreasHeger
    - Acribbs
