{% set name = "pbjasmine" %}
{% set version = "26.1.2" %}
{% set sha256 = "20f2cbc5446fda674c69bba5bd69a00e66b8bd1a374785e02e2f0270e2bb3871" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/PacificBiosciences/jasmine/releases/download/v{{ version }}/jasmine.tar.xz
  sha256: {{ sha256 }}

about:
  home: https://github.com/PacificBiosciences/pbbioconda
  license: BSD-3-Clause-Clear
  summary: jasmine

extra:
  recipe-maintainers:
    - armintoepfer
    - pb-dseifert
  skip-lints:
    #repackaged binary
    - should_be_noarch_generic

build:
  number: 0
  skip: True  # [osx]
  binary_relocation: False
  run_exports:
    - {{ pin_subpackage('pbjasmine', max_pin='x.x') }}
requirements:
  build:
    - {{ compiler('cxx') }}

test:
  commands:
    - jasmine -h
