{% set version = "0.2.4" %}
package:
  name: fufihla
  version: {{ version }}

source:
  url: https://github.com/jingqing-hu/FuFiHLA/archive/refs/tags/v{{ version }}.tar.gz
  sha256: edc1a8509278b818ddc771b65a3c251d1680151cc22577f6bab916568b5fc6db

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage("fufihla", max_pin="x.x") }}
    
requirements:
  host: [] 
  run:
    - python
    - minimap2
    - samtools
    - bcftools
    - htslib    
    - seqtk
    - longcalld ==0.0.4
    - unzip
    - wget 

about:
  home: "https://github.com/jingqing-hu/FuFiHLA"
  summary: HLA typing pipeline for long reads (FuFiHLA) with a location-aware CLI.
  license: MIT
  license_file: LICENSE

test:
  commands:
    - fufihla -h
    - fufihla -h | grep -- '--ont'

extra:
  recipe-maintainers:
    - jingqing-hu
