{% set name = "centrifuger" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

source:
  url: https://github.com/mourisl/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0e42b697c90c6425e8f54f4330b4792d4528147779630c4e36aae67b44898a29

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - zlib
  run:
    - zlib
    - perl
    - wget
    - tar
    - python

test:
  commands:
    - centrifuger -v | grep 'Centrifuger v'
    - centrifuger-inspect 2>&1 | grep 'Required'


about:
  home: https://github.com/mourisl/centrifuger
  license: MIT
  summary: 'Lossless compression of microbial genomes for efficient and accurate metagenomic sequence classification.'

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - doi:10.1101/2023.11.15.567129
