{% set version = "1.3.0" %}

package:
  name: magmax
  version: {{ version }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('magmax', max_pin="x") }}

source:
  url: https://github.com/soedinglab/MAGmax/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 40596b2b2bbe2f219d4599547ada1e9a2421c3bc1463b10d380b5ed74979dd36

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ compiler("rust") }}
    - make
    
  run:
    - skani
    - spades
    - seqtk

test:
  commands:
    - magmax --help

about:
  home: https://github.com/soedinglab/MAGmax
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.md
  summary: MAGmax is a robust tool for dereplicating MAGs through bin merging and reassembly.
    
extra:
  recipe-maintainers:
    - yazhinia
  additional-platforms:
    - linux-aarch64
    - osx-arm64
    
