{% set name = "binge" %}
{% set version = "1.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/zkstewart/BINge/archive/v{{ version }}.tar.gz
  sha256: 9d9d3fabad6f8dfced0158389f143b4beade86fc56c61356575bbd5eafe6d954

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  run:
    - python >=3.9,<=3.13
    - ncls >=0.0.68
    - biopython
    - numpy
    - scikit-learn
    - networkx
    - intervaltree
    - pyfaidx
    - goatools
    - gmap
    - mmseqs2
    - salmon
    - cd-hit

test:
  commands:
    - BINge -h
    - BINge_post -h
    - gmap --help
    - mmseqs -h
    - salmon -h

about:
  home: https://github.com/zkstewart/BINge
  dev_url: https://github.com/zkstewart/BINge
  doc_url: https://github.com/zkstewart/BINge/wiki
  license: GPL-3.0-only
  license_file: LICENSE
  summary: A Python process for clustering transcripts based on locus orthology.
  license_family: GPL
