{% set name = "yame" %}
{% set version = "1.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/zhou-lab/YAME/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f762425ef8fcf4fc8967da7889272f27804af232117931ce524687d7af715136 

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}
  
requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - zlib
    - ncurses

test:
  commands:
    - yame || true

about:
  home: "https://github.com/zhou-lab/YAME"
  license: AGPL-3.0-or-later
  license_family: AGPL
  license_file: LICENSE
  summary: "YAME: Yet Another Methylation Extractor."
  dev_url: "https://github.com/zhou-lab/YAME"
  doc_url: "https://zhou-lab.github.io/YAME"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - Hongxiang2023