{% set name = "squigulator" %}
{% set version = "0.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/hasindu2008/squigulator/releases/download/v{{ version }}/squigulator-v{{ version }}-release.tar.gz
  sha256: f8b428655d586427c6e0c939d4a0383fa8569523234e3c21951edcd23372a66a

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('squigulator', max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
    - wget
  run:
    - zlib

test:
  commands:
    - squigulator --help
    - squigulator --version

about:
  home: https://github.com/hasindu2008/squigulator
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A tool for simulating nanopore raw signal data
  description: 'squigulator is a tool for simulating nanopore raw signal data.'

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
