{% set name = "Slacken" %}
{% set version = "2.0.0" %}
{% set sha256 = "a9fbdee815bb44b3ac00c9b2aa97378fae4bd3b6de0fb30bf117ffc432de90d9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/JNP-Solutions/Slacken/releases/download/v{{ version }}/Slacken-{{version}}.zip
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage("slacken", max_pin="x") }}

requirements:
  run:
    - openjdk >=17,<22
    - pyspark >=3.5.0,<4.0.0

test:
  commands:
    - slacken.sh -h

about:
  home: https://github.com/JNP-Solutions/Slacken
  license: GPL-3.0-only
  license_file: LICENSE.txt
  license_family: GPL3
  summary: Slacken is a very scalable implementation of the Kraken 2 metagenomic classification method, based on Apache Spark. 
  dev_url: https://github.com/JNP-Solutions/Slacken
  doc_url: https://github.com/JNP-Solutions/Slacken/blob/v{{ version }}/README.md

extra:
  identifiers:
    - doi:10.1093/nargab/lqaf076
  recipe-maintainers:
    - jtnystrom

