{% set version = "0.9.4" %}


package:
  name: "nf-test"
  version: {{ version }}

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage("nf-test", max_pin="x.x") }}

source:
  url: https://github.com/askimed/nf-test/releases/download/v{{version}}/nf-test-{{version}}.tar.gz
  sha256: 03d93c1d520fa9b7c764aa92636c2a3a182f67d6926f72b849da0b3b2a41da3f

requirements:
  host:
    - openjdk >=17,<26
    - coreutils
    - curl
  run:
    - openjdk >=17,<26
    - coreutils
    - curl

test:
  commands:
    - nf-test version

about:
  home: 'https://code.askimed.com/nf-test/'
  license: "MIT"
  summary: "nf-test is a simple test framework for Nextflow pipelines."
