{% set name = "ganon" %}
{% set version = "2.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  - url: https://github.com/pirovc/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: f413088fd7233a097358c54b0dbae190898706b42e5eed3129671bbbf47db585
  - folder: libs/robin-hood-hashing
    url: https://github.com/martinus/robin-hood-hashing/archive/refs/tags/3.11.3.tar.gz
    sha256: dcf2b7fa9ef9dd0c67102d94c28e8df3effbe1845e0ed1f31f4772ca5e857fc4

build:
  number: 0
  skip: True  # [py<310 or osx]
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}
  ignore_run_exports:
    - seqan3

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - cmake >=3.5
  host:
    - bzip2
    - catch2 ==2.*
    - coreutils
    - curl
    - cxxopts >=2.2.0
    - diffutils
    - genome_updater >=0.7.0
    - grep
    - multitax >=1.4.0
    - pandas >=1.2.0
    - parameterized >=0.9.0
    - python
    - raptor ==3.*
    - seqan3 ==3.3.0
    - setuptools
    - setuptools_scm
    - zlib
  run:
    - coreutils
    - curl
    - diffutils
    - genome_updater >=0.7.0
    - grep
    - multitax >=1.4.0
    - pandas >=1.2.0
    - python
    - raptor ==3.*

test:
  commands:
    - ganon --help
    - ganon-build --help
    - ganon-classify --help

about:
  home: https://github.com/pirovc/ganon
  summary: "ganon2 classifies genomic sequences against large sets of references efficiently"
  description: |
          ganon2 classifies genomic sequences against large sets of references efficiently,
          with integrated download and update of databases (refseq/genbank), taxonomic profiling
          (ncbi/gtdb), binning and hierarchical classification, customized reporting and more
  license: MIT License
  license_family: MIT
  license_file: LICENSE

extra:
  additional-platforms:
    - linux-aarch64
  identifiers:
    - doi:10.1093/nargab/lqaf094
  recipe-maintainers:
    - pirovc
