{% set name = "bammap2" %}
{% set version = "0.1.5" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  # url: https://static.crates.io/crates/{{ name }}/{{ name }}-{{ version }}.crate
  # sha256: 6a9db161cbe3f99faa0faad449be68e3210b7a49ec657b97d64d8b889f440d84
  url: https://github.com/wangyibin/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0cec3222726b1170ba06ca96202f9fa542069e9d2cc25d30bd1db9bb384a9d83

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('bammap2', max_pin="x") }}


requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - pkg-config
    - clangdev
    - automake
    - autoconf
    - jemalloc
    - make 
    - cargo-bundle-licenses 

test:
  commands:
    - bammap2 --help

about:
  home: https://github.com/wangyibin/bammap2
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "A fast BAM file mapping tool"

extra:
  additional-platforms:
    - linux-aarch64
  recipe-maintainers:
    - wangyibin
