{% set version = "1.0.0" %}
{% set name = "bwa-fastalign" %}
{% set sha256 = "dfe534ebbaaea726b903860c96c33b8a81d7bd8b32e557aec9dc32cd4723b742" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/zzhofict/BWA-FastAlign/archive/refs/tags/v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("bwa-fastalign", max_pin="x") }}
requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - zlib

test:
  commands:
    - bwa-fastalign help
    - bwa-fastalign version

about:
  home: "https://github.com/zzhofict/BWA-FastAlign"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Faster and Cheaper Sequence Alignment on Commercial CPUs (A faster version of bwa-mem with identical outputs)."
  dev_url: "https://github.com/zzhofict/BWA-FastAlign"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - doi:10.1145/3774934.3786421
    - biotools:bwa-fastalign
    - usegalaxy-eu:bwa-fastalign
