{% set name = "buscolite" %}
{% set version = "26.1.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/buscolite-{{ version }}.tar.gz
  sha256: 3c7462c5cb75fb21259b2c1a6ee4ec61ea4bc36491b492d83c0a355bfea94dc7

build:
  number: 0
  noarch: python
  entry_points:
    - buscolite = buscolite.__main__:main
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --no-cache-dir
  run_exports:
    - {{ pin_subpackage('buscolite', max_pin=None) }}

requirements:
  host:
    - python >=3.6
    - pip
    - hatchling
  run:
    - python >=3.6
    - augustus >=3.5.0
    - miniprot
    - natsort
    - pyhmmer >=0.12.0
    - pyfastx >=2.0.0
    - packaging

test:
  imports:
    - buscolite
  commands:
    - buscolite --help

about:
  home: https://github.com/nextgenusfs/buscolite
  summary: 'buscolite: busco analysis for gene predictions.'
  license: "BSD-2-Clause"
  license_family: BSD
  license_file: "LICENSE.md"
  dev_url: https://github.com/nextgenusfs/buscolite

extra:
  recipe-maintainers:
    - nextgenusfs
