{% set name = "hatchet" %}
{% set version = "2.2.0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  - url: https://github.com/raphael-group/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: cf78d2a26212eb80d7eafc2be538ecc5dc7749ca0e20f4c13857086f4c10ebad

  - url: https://packages.gurobi.com/12.0/gurobi12.0.3_linux64.tar.gz  # [not osx]
    sha256: 21bdabbaaf83ce2da42a4f13ecde7a1fd17b6eec4d74c97bad8a051887d11021  # [not osx]
    folder: gurobi1203  # [not osx]

  - url: https://packages.gurobi.com/12.0/gurobi12.0.3_macos_universal2.pkg  # [osx]
    sha256: e1e771e9cf8aa7882b1cdc000be91c2b5fadd18f3fcdd00f2824dd207be09613  # [osx]

build:
  number: 0
  skip: True  # [py < 39 or py > 312]
  entry_points:
    - hatchet = hatchet.__main__:main
  run_exports:
    - {{ pin_subpackage('hatchet', max_pin="x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - python
    - pip
  run:
    - python
    - bcftools
    - biopython
    - hmmlearn
    - kneed
    - matplotlib-base
    - mosdepth
    - numpy >=1.13,<2
    - pandas
    - picard-slim
    - psutil
    - pybedtools
    - pyomo
    - pysam
    - requests
    - samtools
    - seaborn-base
    - scikit-learn
    - scipy
    - statsmodels
    - tabix

test:
  imports:
    - hatchet

about:
  home: "https://github.com/raphael-group/hatchet"
  license: "BSD-3-Clause"
  license_family: BSD
  license_file: LICENSE
  summary: "A package to infer allele and clone-specific copy-number aberrations (CNAs)."
  doc_url: "https://raphael-group.github.io/hatchet"
  dev_url: "https://github.com/raphael-group/hatchet"
  description: |
    HATCHet is an algorithm to infer allele and clone-specific copy-number
    aberrations (CNAs), clone proportions, and whole-genome duplications
    (WGD) for several tumor clones jointly from multiple bulk-tumor samples
    of the same patient or from a single bulk-tumor sample.
