{% set name = "wheezy.template" %}
{% set version = "3.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wheezy_template-{{ version }}.tar.gz
  sha256: c7c0bf85af0f70ca2ef4b6ea9a74ef372f73392aa17bea0d885dcba7356d0867

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv
  entry_points:
    - wheezy.template = wheezy.template.console:main
  run_exports:
    - {{ pin_subpackage('wheezy.template', max_pin="x") }}

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9

test:
  imports:
    - wheezy
  commands:
    - wheezy.template -h 2>&1 | grep "Usage:"

about:
  home: "https://github.com/akornatskyy/wheezy.template"
  summary: "A lightweight template library."
  doc_url: "https://wheezytemplate.readthedocs.io/en/latest"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: "https://github.com/akornatskyy/wheezy.template"
