{% set version = "0.7.0" %}
{% set name = "plasnet" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/leoisl/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: b6cc4d4c69f8de1567093786c3e2ba6e34fbc102c299026af550e483501f43d0

build:
  number: 0
  noarch: python
  script: python -m pip install . --no-deps --ignore-installed -vvv
  entry_points:
    - plasnet = plasnet.plasnet_main:main
  run_exports:
    - {{ pin_subpackage("plasnet", max_pin="x") }}

requirements:
  host:
    - python >=3.9,<3.13
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.9,<3.13
    - networkx >=3.2,<4
    - click >=8.1.7,<9
    - pandas >=2.1.2,<3

test:
  imports:
    - plasnet

  commands:
    - plasnet --help

about:
  home: https://github.com/leoisl/plasnet
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'Clustering, visualising and exploring plasmid networks'

