{% set version = "1.9.7" %}

package:
  name: phast
  version: {{ version }}

source:
  url: https://github.com/CshlSiepelLab/phast/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 78b86fc4234444ed15010c33208cfe48313205962f498bcfe91ece0dd1876892

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('phast', max_pin='x') }}  
  script:
    # --- macOS-only: ensure conda-build uses cctools otool (avoids llvm-otool SIGABRT) ---
    - ln -sf "${BUILD_PREFIX}/bin/${HOST}-otool" "${BUILD_PREFIX}/bin/otool"  # [osx]
    - cmake -S . -B build
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_INSTALL_PREFIX=${PREFIX}
      -DCMAKE_INSTALL_LIBDIR=lib
      -DCMAKE_INSTALL_BINDIR=bin
      -DCMAKE_INSTALL_INCLUDEDIR=include
    - cmake --build build --parallel ${CPU_COUNT}
    - cmake --install build

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make
    - cctools
  host:
    - pcre
    - blas
    - lapack
  run:
    - pcre >=8.45,<9.0a0
    - libopenblas
    
test:
  commands:
    - phastCons --help
    - phyloFit --help

about:
  home: https://github.com/CshlSiepelLab/phast
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "PHAST: Phylogenetic Analysis with Space/Time models"
  description: |
    PHAST is a C-based toolkit for phylogenetic analysis, comparative genomics,
    and evolutionary modeling.

extra:
  recipe-maintainers:
    - asiepel
