{% set name = "genome_updater" %}
{% set version = "0.7.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/pirovc/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 4dff4a65e6a099eacc32621e73a9ba79a51e6e34a3fe71b1024212102d4c5eb8

    
build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}
  noarch: generic

requirements:
  run:
    - tar
    - bc
    - parallel >=20160822
    - gawk
    - coreutils
    - wget
    - findutils
    - curl

test:
  commands:
    - genome_updater.sh -h 2>&1 | grep -e "┌" -e "└" -e "│"

about:
  home: https://github.com/pirovc/genome_updater
  summary: "genome_updater: bash script to download/update snapshots of refseq/genbank"
  description: |
          Bash script to download/update snapshots of files from NCBI genomes repository 
          (refseq/genbank) with track of changes and without redundancy  
  license: MIT License
  license_family: MIT

extra:
  recipe-maintainers:
    - pirovc

