{% set name = "sqz" %}
{% set version = "0.2.0" %}

package:
  name: {{ name | lower }}
  version: {{ version | replace('-', '.') }}

source:
  url: https://github.com/codialab/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d27b76993e99b7466c56c2e15b07d35e421d88fd4ab15d1ecd64eee15a587f60

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - sqz --help

about:
  home: https://github.com/codialab/{{ name }}
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: "sqz is a tool for compressing and decompressing path annotations in GFA files."
  dev_url: https://githubcom/codialab/{{ name }}

extra:
  additional-platforms:
    - osx-arm64
    - linux-aarch64
  recipe-maintainers:
    - heringerp
