{% set name = "evofr" %}
{% set version = "0.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/evofr-{{ version }}.tar.gz
  sha256: 1fb117eaf4a00f581997a84ca56f7160913faaf2de601eea967bad3abae81609

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv
  entry_points:
    - evofr = evofr.cli:main
  run_exports:
    - {{ pin_subpackage('evofr', max_pin="x.x") }}

requirements:
  host:
    - python >=3.9
    - pip
    - poetry-core
  run:
    - python >=3.9
    - numpy >=1.22.4,<2.0.0
    - pandas >=1.4.2,<2.0.0
    - jax >=0.4.14,<0.5.0
    - jaxlib >=0.4.1,<0.5.0
    - numpyro >=0.13.2,<0.14.0
    - blackjax >=0.9.6,<0.10.0
    - matplotlib-base >=3.9,<4
    - seaborn-base >=0.13.2,<0.14.0
    - pyyaml >=5,<7

test:
  imports:
    - evofr
  commands:
    - evofr --help

about:
  home: "https://github.com/blab/evofr"
  dev_url: "https://github.com/blab/evofr"
  license: "AGPL-3.0-or-later"
  license_family: AGPL
  license_file: "LICENSE.txt"
  summary: "Tools for evolutionary forecasting."
  doc_url: "https://github.com/blab/evofr/blob/{{ version }}/README.md"

extra:
  recipe-maintainers:
    - nextstrain-bot
    - huddlej
    - joverlee521
    - marlinfiggins
    - victorlin
