{% set name = "simpleaf" %}
{% set version = "0.20.0" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("simpleaf", max_pin="x.x") }}

source:
  url: https://github.com/COMBINE-lab/simpleaf/archive/v{{ version }}.tar.gz
  sha256: 6b0eae2436905af90f85acf7a0529230b366bc756cfe202c1f98fe5a72e8d21e

requirements:
  build:
    - autoconf
    - automake
    - libtool
    - make
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - pkg-config
  run:
    - alevin-fry >=0.11.2
    - salmon >=1.10.1
    - piscem >=0.12.2

test:
  commands:
    - simpleaf --help || test $? -eq 1

about:
  home: "https://github.com/COMBINE-lab/simpleaf"
  license: "BSD-3-Clause"
  license_family: BSD
  license_file: LICENSE
  summary: "A rust framework to make using alevin-fry even simpler."
  dev_url: "https://github.com/COMBINE-lab/simpleaf"
  doc_url: "https://simpleaf.readthedocs.io/en/latest"

extra:
  additional-platforms:
    - osx-arm64
    - linux-aarch64
