{% set name = "pyranges1" %}
{% set version = "1.3.0" %}
{% set sha256 = "63061402c6cc8721e020d5d26d5dd25e17925ef11a05f78778c0871e0627e955" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - pyranger = pyranges1.cli:main
  run_exports:
    - {{ pin_subpackage('pyranges1', max_pin='x.x') }}

requirements:
  host:
    - python >=3.12
    - pip
    - setuptools >=61
    - wheel
    - setuptools-scm >=6.2
  run:
    - python >=3.12
    - pyrle >=0.0.41
    - bamread
    - pybigwig
    - pandas
    - tabulate
    - natsort
    - ruranges >=0.1.1

test:
  imports:
    - pyranges1
  commands:
    - python -c "import pyranges1 as pr; print(pr.__version__)"
  requires:
    - python >=3.12

about:
  home: http://github.com/pyranges/pyranges_1.x
  summary: GenomicRanges for Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - endrebak
