package:
  name: msstitch
  version: "3.19"

source:
  url: https://files.pythonhosted.org/packages/11/51/07b2dde0a1a42fc8310dbf6ae71910233718eab3747eafdfeb246928be70/msstitch-3.19.tar.gz
  sha256: 178ff8de80ab34383bb3f5903dfb4e199c17a100fb2eeb8b191b27b44e319a37

build:
  noarch: python
  number: 0
  entry_points:
    - msstitch=app.msstitch:main
  run_exports:
    - {{ pin_subpackage('msstitch', max_pin="x") }}

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - numpy
    - lxml
    - biopython >=1.69
    ## can be removed if the upstream package includes libgcc at some point

test:
  imports:
    - app
    - app.actions
    - app.actions.lookups
    - app.actions.psmtable
    - app.actions.percolator
    - app.dataformats
    - app.drivers
    - app.lookups
    - app.lookups.sqlite
    - app.readers
    - app.writers

  commands:
    - msstitch --help

about:
  home: https://github.com/lehtiolab/msstitch
  license: MIT
  summary: "MS proteomics post processing utilities."
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/lehtiolab/msstitch
