{% set name = "vartovcf" %}
{% set version = "1.5.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/clintval/{{ name }}/archive/{{ version }}.tar.gz
  sha256: aee2646f0db41bd2525d46d7daa291892e14cd517a18b2b7a09d31f7004107ff

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - clangdev
    - pkg-config
    - make
    - cmake

test:
  commands:
    - vartovcf --help

about:
  home: "https://github.com/clintval/{{ name }}"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Convert variants from VarDict/VarDictJava into VCF v4.2 format."
  dev_url: "https://github.com/clintval/{{ name }}"
  doc_url: "https://github.com/clintval/{{ name }}/blob/{{ version }}/README.md"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - clintval
