{% set name = "predictosaurus" %}
{% set version = "0.9.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/fxwiegand/predictosaurus/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5e12f8f0b1e3cc0c0cab4c7d161545735a7fc7d5023d8cc09f898bdc74b93d6f

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('predictosaurus', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - pkg-config
    - make
    - cmake
    - clangdev <22
  host:
    - gsl
    - libcblas
    - libcurl
    - openssl  # [not osx]

test:
  commands:
    - predictosaurus --help

about:
  home: "https://github.com/fxwiegand/predictosaurus"
  license: MIT
  license_family: MIT
  summary: "Predictosaurus is a command-line tool designed for uncertainty-aware haplotype-based genomic variant effect prediction."
  dev_url: "https://github.com/fxwiegand/predictosaurus"
  doc_url: "https://github.com/fxwiegand/predictosaurus/blob/v{{ version }}/README.md"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - fxwiegand
    - felixmoelder
    - johanneskoester
