{% set name = "orthofinder" %}
{% set version = "3.1.3" %}
{% set sha256 = "ee93572b613510755e706310c7478150dd78d0ab0200de892993d67a568646c8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/OrthoFinder/OrthoFinder/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  run:
    - python >=3.11,<=3.14
    - numpy
    - scipy
    - scikit-learn
    - biopython
    - ete4
    - rich
    - blast
    # https://github.com/davidemms/OrthoFinder/issues/826 https://github.com/bbuchfink/diamond/issues/707
    - diamond <2.2|>=2.1.7
    - mcl
    - fastme
    - mafft
    - fasttree
    - muscle <5
    - raxml
    - raxml-ng
    - iqtree
    - bzip2
    - mmseqs2
    - aster
    - famsa

test:
  source_files:
    - ExampleData
    - ExampleData/*
  commands:
    - orthofinder -h
    - orthofinder -v

about:
  home: "https://github.com/OrthoFinder/OrthoFinder"
  summary: "Accurate inference of orthogroups, orthologues, gene trees and rooted species tree made easy!"
  license: "GPL-3.0-only"
  license_file: LICENSE
  license_family: GPL3
  dev_url: "https://github.com/OrthoFinder/OrthoFinder"
  doc_url: "https://orthofinder.github.io/OrthoFinder"
