{% set name = "tw"%}
{% set version = "0.22.0" %}
{% set sha256 = "8115578bf937e4479512cd2dd9a5f8a5052e650b0f4f355f6e6261927f47140f" %}

package:
  name: tower-cli
  version: {{ version }}

source:
  url: https://github.com/seqeralabs/tower-cli/releases/download/v{{ version }}/tw-jar.jar
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage("tower-cli", max_pin="x.x") }}

requirements:
  run:
    - openjdk >=17

test:
  commands:
    - tw --help
    - tw organizations --help

about:
  home: "https://github.com/seqeralabs/tower-cli"
  license: "Apache-2.0"
  license_family: APACHE
  license_file: "LICENSE.txt"
  summary: "The Tower CLI an interface to Nextflow Tower via the CLI."
  dev_url: "https://github.com/seqeralabs/tower-cli"
  doc_url: "https://docs.seqera.io/platform-cloud/platform-cloud"
