{% set name = "shiba" %}
{% set version = "0.8.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/Sika-Zheng-Lab/Shiba/archive/refs/tags/v{{ version }}.tar.gz
  sha256: de9f74d6e938371bf3e4e072378c2dd419085579ff4e5bc9d0299764e31961aa

build:
  number: 0
  noarch: generic
  script:
    - mkdir -p ${PREFIX}/bin
    - mkdir -p ${PREFIX}/share/${PKG_NAME}-${PKG_VERSION}-${PKG_BUILDNUM}
    - cp -rf ${SRC_DIR}/* ${PREFIX}/share/${PKG_NAME}-${PKG_VERSION}-${PKG_BUILDNUM}/
    - chmod 0755 ${PREFIX}/share/${PKG_NAME}-${PKG_VERSION}-${PKG_BUILDNUM}/shiba.py
    - chmod 0755 ${PREFIX}/share/${PKG_NAME}-${PKG_VERSION}-${PKG_BUILDNUM}/scshiba.py
    - ln -sf ${PREFIX}/share/${PKG_NAME}-${PKG_VERSION}-${PKG_BUILDNUM}/shiba.py ${PREFIX}/bin/shiba.py
    - ln -sf ${PREFIX}/share/${PKG_NAME}-${PKG_VERSION}-${PKG_BUILDNUM}/scshiba.py ${PREFIX}/bin/scshiba.py
  run_exports:
    - {{ pin_subpackage("shiba", max_pin="x.x") }}

requirements:
  host:
    - python >=3.11.0,<3.13.0
  run:
    - python >=3.11.0,<3.13.0
    - pandas >=1.5.3,<3.0.0
    - statsmodels >=0.13.5,<1.0.0
    - numexpr >=2.8.4,<3.0.0
    - pysam >=0.23.0,<1.0.0
    - scanpy >=1.9.5,<2.0.0
    - numpy >=1.26.4,<2.0.0
    - pyyaml >=6.0.2,<7.0.0
    - regtools >=1.0.0,<2.0.0
    - subread >=2.0.8,<3.0.0
    - stringtie >=3.0.0,<4.0.0
    - plotly >=5.13.0,<6.0.0
    - r-base >=4.1.3,<5.0.0
    - bioconductor-deseq2 >=1.34.0,<2.0.0
    - r-locfit >=1.5_9.4,<2.0.0
    - r-data.table >=1.14.2,<2.0.0

test:
  commands:
    - shiba.py -h > /dev/null
    - scshiba.py -h > /dev/null

about:
  home: "https://github.com/Sika-Zheng-Lab/Shiba"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A versatile method for systematic identification of differential RNA splicing across platforms"
  description: |
    A versatile computational method for systematic identification of differential RNA splicing.
    Shiba/scShiba can quantify and identify differential splicing events from bulk RNA-seq data and single-cell RNA-seq data.
    Shiba and scShiba are also implemented as Snakemake workflows, SnakeShiba and SnakeScShiba, respectively.
  dev_url: "https://github.com/Sika-Zheng-Lab/Shiba"
  doc_url: "https://sika-zheng-lab.github.io/Shiba"

extra:
  recipe-maintainers:
    - NaotoKubota
