{% set version = "1.5.0" %}
{% set sha256 = "26a8700c55ed4961e563bf34cfce93b2120742100d8d7cc197b43ae6f3d6ec92" %}

package:
  name: raxtax
  version: {{ version }}

source:
  url: https://github.com/noahares/raxtax/releases/download/v{{ version }}/source.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('raxtax', max_pin="x") }}

requirements:
  build:
    - {{ compiler('rust') }}

test:
  commands:
    - raxtax --version

about:
  home: https://github.com/noahares/raxtax
  license: AGPL-3.0-or-later
  license_family: AGPL
  license_file:
    - LICENSE
  summary: raxtax is a k-mer-based non-Bayesian Taxonomic Classifier.
