{% set name = "longphase" %}
{% set version = "2.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/twolinin/longphase/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 481040c7f22f91fb5e3aa25bab8ac1eed2d04dc8d432aa8c4861aa9ca7f0fff9

build:
  number: 0
  skip: True  # [osx]
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - libtool
    - pkg-config
    - make
    - cmake
  host:
    - zlib
    - bzip2
    - xz

test:
  commands:
    - longphase

about:
  home: "https://github.com/twolinin/longphase"
  license: "GPL-3.0-only"
  license_family: GPL3
  license_file: LICENSE
  summary: "LongPhase is an ultra-fast program for simultaneously co-phasing SNPs, small indels, large SVs, and (5mC) modifications for Nanopore and PacBio platforms."
  dev_url: "https://github.com/twolinin/longphase"
extra:
   additional-platforms:
     - linux-aarch64
     - osx-arm64
