{% set version = "2.8.4" %}
{% set sha256 = "0ea1091560837870dd59eb1b11246a1817c8ac1822530bd9ae607343a5163596" %}

package:
  name: svdb
  version: {{ version }}

source:
  url: https://github.com/J35P312/SVDB/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - svdb = svdb.__main__:main
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation --no-cache-dir . -vvv
  run_exports:
    - {{ pin_subpackage('svdb', max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython
    - setuptools
  run:
    - python
    - numpy

test:
  commands:
    - svdb --help

about:
  home: "https://github.com/J35P312/SVDB"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Structural variant database software."
  dev_url: "https://github.com/J35P312/SVDB"
  doc_url: "https://github.com/J35P312/SVDB/blob/{{ version }}/README.md"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
