{% set name = "jcvi" %}
{% set version = "1.6.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4701a2909ade5313b774d9a85801c4cbca782144a91f0a2adff0fecfe95125cc

build:
  number: 0
  skip: True  # [osx or py > 312]
  entry_points:
    - jcvi = jcvi.cli:main
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools-scm
    - cython
    - numpy
    - hatchling
    - hatch-vcs
  run:
    - python
    - biopython
    - boto3
    - palettable
    - crossmap
    - deap
    - ete3
    - ftpretty
    #- genomepy
    - gffutils
    - goatools
    - python-graphviz
    - jinja2
    - imagemagick
    - libmagic
    - matplotlib-base
    - more-itertools
    - natsort
    - networkx
    - numpy
    #- ortools-python
    - pybedtools
    - pyefd
    - pypdf
    - pytesseract
    - rich
    - scikit-image
    - scipy
    - seaborn-base
    - wand
    - webcolors
    - last
    - r-ggplot2
    - r-tinytex
    - ucsc-liftover

test:
  imports:
    - jcvi
    - jcvi.algorithms
    - jcvi.annotation
    - jcvi.apps
    - jcvi.assembly
    - jcvi.compara
    - jcvi.formats
    - jcvi.graphics
    - jcvi.projects
    - jcvi.utils
    - jcvi.utils.data
    - jcvi.variation
  commands:
    - jcvi --help

about:
  home: "https://github.com/tanghaibao/jcvi"
  license: "BSD-2-Clause"
  license_family: BSD
  license_file: LICENSE
  summary: "Python utility libraries on genome assembly, annotation, and comparative genomics."
  description: "JCVI utility libraries"
  dev_url: "https://github.com/tanghaibao/jcvi"
  doc_url: "https://github.com/tanghaibao/jcvi/wiki"

extra:
  additional-platforms:
    - linux-aarch64
  identifiers:
    - doi:10.1002/imt2.211
