{% set name = "seqnado" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/seqnado-{{ version }}.tar.gz
  sha256: 2183f9656170a396e939e8ba7a18dd14478a3c36b8de38cdc7bdeb1382bf3a8f

build:
  number: 0
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . --no-deps -vvv
  entry_points:
    - seqnado = seqnado.cli:app
  run_exports:
    - {{ pin_subpackage('seqnado', max_pin="x.x") }}

requirements:
  host:
    - python >=3.10
    - setuptools >=61.0
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - numpy >=1.24, <=2.1.0
    - pandas >=2.0, <=2.3.3
    - pandera
    - pulp <=2.9.0
    - pydantic
    - pyranges
    - pyyaml
    - seaborn
    - setuptools_scm
    - snakemake >=9.12.0, <=9.14.5
    - snakemake-executor-plugin-slurm
    - snakemake-wrapper-utils
    - tracknado
    - wget

test:
  imports:
    - seqnado
  commands:
    - seqnado --help

about:
  home: https://github.com/Milne-Group/SeqNado
  summary: "A unified and user-friendly collection of pipelines for: ATAC-seq, ChIP-seq, CUT&RUN/TAG, RNA-seq, WGS, Methylation (Bisulphite/TAPS), CRISPR screens and Micro-Capture-C."
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - alsmith151
    - CChahrour
