{% set version = "0.88.1" %}

package:
  name: multivcfanalyzer
  version: {{ version }}

source:
 url: https://github.com/alexherbig/MultiVCFAnalyzer/releases/download/v{{ version }}/MultiVCFAnalyzer-{{ version }}.jar
 sha256: 5b7aceeacf0e7e0dce94ae6eb032771d567de56cc3e104a484f0a3e40707ee1e

build:
    noarch: generic
    number: 0
    run_exports:
      - {{ pin_subpackage("multivcfanalyzer", max_pin="x.x") }}

requirements:
  run:
    - openjdk
    - python

test:
  commands:
  - multivcfanalyzer --help

about:
  license: GPL >=3
  license_family: GPL
  summary: MultiVCFAnalyzer is a VCF file post-processing tool tailored for aDNA. License on Github repository.
  home: https://github.com/alexherbig/MultiVCFAnalyzer
