{% set version = "1.0.0" %}
{% set sha256 = "6a9aecf0d926bd280a489f29c86e3e26e054712b018e36d9c1b5f7b5e5e1d1c5" %}

package:
  name: foldcomp
  version: {{ version }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('foldcomp', max_pin="x.x") }}

source:
  url: https://github.com/steineggerlab/foldcomp/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - foldcomp > /dev/null

about:
  home: https://github.com/steineggerlab/foldcomp
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: "Foldcomp: a library and format for compressing and indexing large protein structure sets"

extra:
  identifiers:
    - doi:10.1093/bioinformatics/btad153
  recipe-maintainers:
    - milot-mirdita
  additional-platforms:
    - linux-aarch64
    - osx-arm64
