{% set name = "starcatpy" %}
{% set version = "1.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/starcatpy-{{ version }}.tar.gz
  sha256: ff1b7e7a6d3e9432a7a8443bff810a44780bda188722388a6565ae09c03d4186

build:
  entry_points:
    - starcat = starcat:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --no-cache-dir
  number: 0
  run_exports:
    - {{ pin_subpackage('starcatpy', max_pin="x") }}

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - scikit-learn >=1.0
    - anndata
    - pandas
    - numpy
    - scipy
    - pyyaml
    - requests

test:
  imports:
    - starcat
  commands:
    - starcat --help

about:
  home: https://github.com/immunogenomics/starCAT
  summary: "Implements *CellAnnotator (aka *CAT/starCAT), annotating scRNA-Seq with predefined gene expression programs."
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/immunogenomics/starCAT
